name: Actualizar datos de audiencia

on:
  schedule:
    # Ejecutar a las 9:00 AM UTC (11:00 AM en España) de lunes a viernes
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyGithub

      - name: Ejecutar script de actualización
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
          FILE_PATH: "tv_ratings.json"
          DATA_SOURCE_URL: ${{ secrets.DATA_SOURCE_URL }}
          START_DATE: "2024-09-09"
        run: |
          python update_ratings.py